// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: "doc",
      id: "cours/rencontre1", // Doit matcher le nom du document qui est dans docs/01-cours/. Les chiffres au début (ex : 01-) sont ignorés.
      customProps: { // Attention, il faut recompiler à chaque modification dans sidebar.js pour que les modifications s'appliquent.
        calendrier: {
          "Simon": [
            {"grp1": "2026-08-21"}
          ]
        },
        tooltip: "visible" // Valeurs possibles visible ou cache, valeur par défaut "visible"
      }
    },
    {
      type: "doc",
      id: "cours/rencontre2",
      customProps: {
        calendrier: {
          "Simon": [
            {"grp1": "2026-08-28"}
          ]
        }
      }
    },
    {
      type: "doc",
      id: "cours/rencontre3",
      customProps: {
        calendrier: {
          "Simon": [
            {"grp1": "2026-09-04"},
          ]
        }
      }
    },
    {
      type: "doc",
      id: "cours/rencontre4",
      customProps: {
        calendrier: {
          "Simon": [
            {"grp1": "2026-09-11"}
          ]
        }
      }
    },
    {
      type: "doc",
      id: "cours/rencontre5",
      customProps: {
        calendrier: {
          "Simon": [
           {"grp1": "2026-09-18"}
          ]
        }
      }
    },
    {
      type: "doc",
      id: "cours/rencontre6",
      customProps: {
        calendrier: {
          "Simon": [
            {"grp1": "2026-09-25"}          ]
        }
      }
    },
    {
      type: "doc",
      id: "cours/rencontre7",
      customProps: {
        calendrier: {
          "Simon": [
            {"grp1": "2026-09-02"}
          ]
        }
      },
      "className": "remise-tp1"
    },
    {
      type: "doc",
      id: "cours/rencontre8",
      customProps: {
        calendrier: {
          "Simon": [
            {"grp1": "2026-10-09"}
          ]
        }
      },
      "className": "examen"
    },
    {
      type: "doc",
      id: "cours/rencontre9",
      customProps: {
        calendrier: {
          "Simon": [
           {"grp1": "2026-10-16"}
          ]
        },
        tooltip: "cache"
      }
    },
    {
      type: "doc",
      id: "cours/rencontre10",
      customProps: {
        calendrier: {
          "Simon": [
            {"grp1": "2026-10-23"}
          ]
        },
        tooltip: "cache"
      }
    },
    {
      type: "doc",
      id: "cours/rencontre11",
      customProps: {
        calendrier: {
          "Simon": [
            {"grp1": "2026-10-30"}
          ]
        },
        tooltip: "cache"
      }
    },
    {
      type: "doc",
      id: "cours/rencontre12",
      customProps: {
        calendrier: {
          "Simon": [
           {"grp1": "2026-11-06"}
          ]
        },
        tooltip: "cache"
      },
      "className": "remise-tp2-partielle"
    },
    {
      type: "doc",
      id: "cours/rencontre13",
      customProps: {
        calendrier: {
          "Simon": [
            {"grp1": "2026-11-13"}
          ]
        },
        tooltip: "cache"
      }
    },
    {
      type: "doc",
      id: "cours/rencontre14",
      customProps: {
        calendrier: {
          "Simon": [
            {"grp1": "2026-11-20"}
          ]
        },
        tooltip: "cache"
      }
    },
    {
      type: "doc",
      id: "cours/rencontre15",
      customProps: {
        calendrier: {
          "Simon": [
            {"grp1": "2026-11-27"}
          ]
        },
        tooltip: "cache"
      },
      "className": "remise-tp2-finale"
    }
  ],
  "tp": [
    {
      type: "autogenerated",
      "dirName": "02-tp"
    }
  ],
  "recettes": [
    {
      type: "autogenerated",
      "dirName": "03-recettes"
    }
  ],
  "aidememoire": [
    {
      type: "autogenerated",
      "dirName": "04-aidememoire"
    }
  ]
};

module.exports = sidebars;
